services:
  dt-labs:
    image: timescale/timescaledb-ha:pg15
    container_name: dt-labs
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD} 
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
    ports:
      - 5432:5432
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./init-timescale.sql:/docker-entrypoint-initdb.d/init-timescale.sql
  
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  dt-test:
    image: timescale/timescaledb-ha:pg15
    container_name: test
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD} 
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
    ports:
      - 54323:54323
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./init-timescale.sql:/docker-entrypoint-initdb.d/init-timescale.sql

volumes:
  timescale_data:
  redis_data:
