services:
  dt-labs:
    build: .
    container_name: dt-labs
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD} 
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
    ports:
      - 5432:5432
    volumes:
      - timescale_data:/var/lib/postgresql/data

volumes:
  timescale_data:
