services:
  dt-labs:
    image: postgres:15-alpine
    container_name: dt-labs
    env_file:
    - .env
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD} 
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
    ports:
      - 5432:5432