services:
  dt-labs:
    image: timescale/timescaledb-ha:pg15
    container_name: dt-labs
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD} 
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"] 
      interval: 15s
      timeout: 1s 
      retries: 5
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./init-timescale.sql:/docker-entrypoint-initdb.d/init-timescale.sql
  
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  timescale_data:
  redis_data:
